// Write a function named tribonacci that takes a signature array and a non-negative integer n as inputs,
// returning the first n elements of a Tribonacci sequence generated by summing the last 3 numbers of the sequence, 
//starting with the provided signature array.



function tribonacci(signature, n) {
    let result = [];

    if (n === 0) {
        return [];
    }

    result = result.concat(signature);

    for (let i = 3; i < n; i++) {
        const nextElement = result.slice(-3).reduce((acc, val) => acc + val, 0);
        result.push(nextElement);
    }

    return result.slice(0, n);
}

const signature = [1, 1, 1];
const n = 10;
console.log(tribonacci(signature, n));  //  [1, 1, 1, 3, 5, 9, 17, 31, 57, 105]
